name = "Tetsing Modpack2"
creator = "TenBitMelon"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ZTAzMWY2ZmQ4ZTJlNDJhOWUyZmE4NzVhNzYwODI0OTVmMDk0YmNjM2NhYTIxNDZkMzMyY2M5NDgwNDhjOTNhMA=="

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"