name = "Tetsing Modpack2"
creator = "TenBitMelon"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "MjY4ZTEwNzBjNDlmNmQ3NzlmYjJmMDEzMWRjMGM1MWU0M2E0YWMzNDBhZjYzZGRhOTE2YzJkOTE0OGY1NGU1Mg=="

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"